name: Testing

permissions:
  contents: read
  pull-requests: read

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  
  workflow_dispatch:
    inputs:
      node-version:
        default: '18.x'
        type: string
        description: Node.js version
        required: false

jobs:
  test:
    name: Linting & Testing
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ^7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ github.event.inputs.node-version || '18.x' }}
          cache: 'pnpm'

        # https://github.com/dependabot/dependabot-core/issues/1736
      - name: Dependency installation
        run: pnpm install

      - name: Type checking
        run: pnpm test

      - name: Linting
        run: pnpm lint